
  CREATE TABLE "ADMIN"."ACTIVITY" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"COLUMN_NAME" VARCHAR2(30 BYTE), 
	"OLD_DATE" VARCHAR2(500 BYTE), 
	"NEW_DATA" VARCHAR2(500 BYTE), 
	"PERFORMBY" VARCHAR2(10 BYTE), 
	"PDATE" DATE, 
	 CONSTRAINT "ACTIVITY_FK2" FOREIGN KEY ("PERFORMBY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
-----

  CREATE TABLE "ADMIN"."ALLVIEW" 
   (	"VIEW_ID" NUMBER NOT NULL ENABLE, 
	"QUERY" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"ALIAS" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ADATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"A" VARCHAR2(1 BYTE), 
	 CONSTRAINT "ALLVIEW_PK" PRIMARY KEY ("VIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."AMBASSADOR" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"INSERTBY" VARCHAR2(20 BYTE), 
	"INSERTDATE" DATE, 
	 CONSTRAINT "AMBASSADOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "AMBASSADOR_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
------

  CREATE TABLE "ADMIN"."BANK" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ACCOUNT_NO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"BANK_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"REFERENCES" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NOMINY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ADD_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ADATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"SNO" NUMBER, 
	 CONSTRAINT "PKBANK" PRIMARY KEY ("ACCOUNT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "BANK_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "BANK_FK2" FOREIGN KEY ("NOMINY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "BANK_FK3" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "BANK_FK4" FOREIGN KEY ("REFERENCES")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
-----

  CREATE TABLE "ADMIN"."CONTACTS" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"REFER" VARCHAR2(10 BYTE), 
	"ADD_BY" VARCHAR2(10 BYTE), 
	"ADATE" DATE DEFAULT sysdate, 
	"SNO" NUMBER, 
	 CONSTRAINT "CONTACTS_PK" PRIMARY KEY ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CONTACTS_FK1" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "CONTACTS_FK2" FOREIGN KEY ("REFER")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."CRMINAL" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CRIME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DETAILS" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ADD_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ADATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"SNO" NUMBER, 
	 CONSTRAINT "CRMINAL_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "CRMINAL_FK2" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."CURRENT_ADDRESS" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"ADD_BY" VARCHAR2(10 BYTE), 
	"ADD_DATE" DATE, 
	 CONSTRAINT "CURRENT_ADDRESS_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "CURRENT_ADDRESS_FK2" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."DELETE_HIS" 
   (	"DATA" VARCHAR2(150 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"P_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
-----

  CREATE TABLE "ADMIN"."DISABLE_PEOPLE" 
   (	"USER_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DETAILS" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"ADD_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"A_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "DISABLE_PEOPLE_FK1" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "DISABLE_PEOPLE_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 -----
 
  CREATE TABLE "ADMIN"."DREP" 
   (	"ID" VARCHAR2(10 BYTE), 
	"CID" VARCHAR2(10 BYTE), 
	 CONSTRAINT "DREP_FK2" FOREIGN KEY ("CID")
	  REFERENCES "ADMIN"."ELECTION_CANDIDATE" ("USER_ID") ENABLE, 
	 CONSTRAINT "DREP_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."VOTER_LIST" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."DUEVOTE" 
   (	"ID" VARCHAR2(10 BYTE), 
	"POST" VARCHAR2(20 BYTE), 
	 CONSTRAINT "DUEVOTE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."VOTER_LIST" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 -----
 
  CREATE TABLE "ADMIN"."E_P_BY" 
   (	"NAME" VARCHAR2(30 BYTE), 
	"P_NAME" VARCHAR2(30 BYTE), 
	"DATA" VARCHAR2(500 BYTE), 
	"PDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ----
 
  CREATE TABLE "ADMIN"."EDUCATION" 
   (	"ID" VARCHAR2(10 BYTE), 
	"DETAILS" VARCHAR2(200 BYTE), 
	"ACADEMIC_CODE" VARCHAR2(15 BYTE), 
	"ADD_DATE" DATE, 
	"LEV" VARCHAR2(5 BYTE), 
	"ADD_BY" VARCHAR2(10 BYTE), 
	"GRADUATE" VARCHAR2(1 BYTE), 
	"SNO" NUMBER, 
	 CONSTRAINT "EDUCATION_FK1" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "EDUCATION_FK2" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."ELECTION_CANDIDATE" 
   (	"USER_ID" VARCHAR2(10 BYTE), 
	"SYMBOL_NAME" VARCHAR2(20 BYTE), 
	"SYMBOL_IMAGE" CLOB, 
	"POST" VARCHAR2(20 BYTE), 
	"ZONE" NUMBER, 
	"CURRENT_" VARCHAR2(1 BYTE), 
	"INSERT_BY" VARCHAR2(10 BYTE), 
	"IDATE" DATE, 
	 CONSTRAINT "ECANDIDATEPK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ELECTION_CANDIDATE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "ELECTION_CANDIDATE_FK2" FOREIGN KEY ("INSERT_BY")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SYMBOL_IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 
----

  CREATE TABLE "ADMIN"."FINGER_PRINT" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PRINT" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"UPDATE_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"UPDATE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "FINGER_PRINT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FINGER_PRINT_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FINGER_PRINT_FK2" FOREIGN KEY ("UPDATE_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ----
 
  CREATE TABLE "ADMIN"."FOREIGNER" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"PASSPORT" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"CONTACT" VARCHAR2(20 BYTE), 
	"BLOOD_GROUP" VARCHAR2(20 BYTE), 
	"INSERT_DATE" DATE, 
	"INSERT_BY" VARCHAR2(10 BYTE), 
	 CONSTRAINT "FOREIGNER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FOREIGNER_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "FOREIGNER_FK2" FOREIGN KEY ("INSERT_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."G_LIINK" 
   (	"ID" VARCHAR2(10 BYTE), 
	"L_ID" VARCHAR2(10 BYTE), 
	 CONSTRAINT "G_LIINK_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "G_LIINK_FK2" FOREIGN KEY ("L_ID")
	  REFERENCES "ADMIN"."LINK" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ----
 
  CREATE TABLE "ADMIN"."G_VIEW" 
   (	"USER_ID" VARCHAR2(10 BYTE), 
	"VIEW_ID" NUMBER, 
	 CONSTRAINT "G_VIEW_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "G_VIEW_FK2" FOREIGN KEY ("VIEW_ID")
	  REFERENCES "ADMIN"."ALLVIEW" ("VIEW_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."IMAGE" 
   (	"ID" VARCHAR2(10 BYTE), 
	"IMAGE" CLOB, 
	"INSERT_BY" VARCHAR2(10 BYTE), 
	"I_DATE" DATE, 
	 CONSTRAINT "IMAGE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "IMAGE_FK2" FOREIGN KEY ("INSERT_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

 ---
 
  CREATE TABLE "ADMIN"."LINK" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"LINK" VARCHAR2(150 BYTE), 
	"A_DATE" DATE DEFAULT sysdate, 
	"ALIAS" VARCHAR2(50 BYTE), 
	 CONSTRAINT "LINK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
-----

  CREATE TABLE "ADMIN"."LOAN" 
   (	"DONER" VARCHAR2(10 BYTE), 
	"RECEIVER" VARCHAR2(10 BYTE), 
	"DETAILS" VARCHAR2(200 BYTE), 
	"CLEARDATE" DATE, 
	"REFERNCES" VARCHAR2(10 BYTE), 
	"NOMINY" VARCHAR2(10 BYTE), 
	"INSERTBY" VARCHAR2(10 BYTE), 
	"IDATE" DATE, 
	"SCANFILE" NUMBER NOT NULL ENABLE, 
	"SNO" NUMBER, 
	 CONSTRAINT "LOAN_PK" PRIMARY KEY ("SCANFILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "LOAN_FK1" FOREIGN KEY ("REFERNCES")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "LOAN_FK2" FOREIGN KEY ("DONER")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "LOAN_FK3" FOREIGN KEY ("RECEIVER")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "LOAN_FK4" FOREIGN KEY ("INSERTBY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "LOAN_FK5" FOREIGN KEY ("NOMINY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "LOAN_FK6" FOREIGN KEY ("SCANFILE")
	  REFERENCES "ADMIN"."SCANING" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ----

  CREATE TABLE "ADMIN"."MARRIED" 
   (	"MALE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FEMALE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DETAILS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"ADD_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"M_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"DEVORSE" DATE, 
	"SNO" NUMBER, 
	 CONSTRAINT "MARRIED_FK1" FOREIGN KEY ("MALE")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "MARRIED_FK2" FOREIGN KEY ("FEMALE")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "MARRIED_FK3" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----
 
  CREATE TABLE "ADMIN"."NOTICE" 
   (	"NOTICEBY" VARCHAR2(10 BYTE), 
	"NOTICEFOR" VARCHAR2(10 BYTE), 
	"DETAILS" VARCHAR2(500 BYTE), 
	"EXEDATE" DATE, 
	"INSERTDATE" DATE, 
	"SCAFILEID" NUMBER, 
	"EXE" VARCHAR2(1 BYTE), 
	 CONSTRAINT "NOTICE_FK1" FOREIGN KEY ("SCAFILEID")
	  REFERENCES "ADMIN"."SCANING" ("ID") ENABLE, 
	 CONSTRAINT "NOTICE_FK2" FOREIGN KEY ("NOTICEBY")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "NOTICE_FK3" FOREIGN KEY ("NOTICEFOR")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ----
 
  CREATE TABLE "ADMIN"."P_FINGER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PRINT" VARCHAR2(500 BYTE), 
	"CH_DATE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "P_FINGER_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."FINGER_PRINT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."PASSPORT" 
   (	"USER_ID" VARCHAR2(10 BYTE), 
	"VERIFIED_BY" VARCHAR2(10 BYTE), 
	"VDATE" DATE, 
	"PASSPORT_TYPE" VARCHAR2(10 BYTE), 
	 CONSTRAINT "PASSPOSRPK1" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PASSPORT_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "PASSPORT_FK2" FOREIGN KEY ("VERIFIED_BY")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."PAY_TAX" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AMMOUNT" NUMBER NOT NULL ENABLE, 
	"ADD_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"A_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "PAY_TAX_FK2" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "PAY_TAX_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TEX" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ----
 
  CREATE TABLE "ADMIN"."PEOPLE" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NAME_ENG" CLOB, 
	"NAME_BAN" CLOB NOT NULL ENABLE, 
	"GENDER" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FATHER" VARCHAR2(10 BYTE), 
	"MOTHER" VARCHAR2(10 BYTE), 
	"DOB" DATE NOT NULL ENABLE, 
	"DEAD" DATE, 
	"BLOOD_GROUP" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PEOPLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PEOPLE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "PEOPLE_FK2" FOREIGN KEY ("FATHER")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "PEOPLE_FK3" FOREIGN KEY ("MOTHER")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("NAME_ENG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NAME_BAN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

  CREATE OR REPLACE TRIGGER "ADMIN"."EXECUTE_WILL_NOTICE" after update of dead on people
for each row
begin



if(:new.dead is null)then
update tab_user set type='lock' where user_id=:old.id;
else
update notice set exedate=sysdate where noticeby=:old.id and exedate is null;
update tab_user set type='dead' where user_id=:old.id;
end if;
end;
/
ALTER TRIGGER "ADMIN"."EXECUTE_WILL_NOTICE" ENABLE;
 
----

  CREATE TABLE "ADMIN"."PERMANENT_ADDRESS" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"ADD_BY" VARCHAR2(10 BYTE), 
	"ADD_DATE" DATE, 
	 CONSTRAINT "PERMANENT_ADDRESS_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "PERMANENT_ADDRESS_FK2" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ---
 
  CREATE TABLE "ADMIN"."PROCEDURE_DBM" 
   (	"PROCEDURE_NAME" VARCHAR2(30 BYTE), 
	"PARAMETER" VARCHAR2(70 BYTE), 
	"LOCK_USER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."PROPERTY" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PROPERTYID" NUMBER NOT NULL ENABLE, 
	"CURRENTSTATUS" VARCHAR2(100 BYTE), 
	"DETAILS" VARCHAR2(500 BYTE), 
	"INSERTBY" VARCHAR2(20 BYTE), 
	"IDATE" DATE, 
	"SNO" NUMBER, 
	 CONSTRAINT "PROPERTY_PK" PRIMARY KEY ("PROPERTYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PROPERTY_FK1" FOREIGN KEY ("PROPERTYID")
	  REFERENCES "ADMIN"."SCANING" ("ID") ENABLE, 
	 CONSTRAINT "PROPERTY_FK2" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "PROPERTY_FK3" FOREIGN KEY ("INSERTBY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."REPUTATION" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"GOOD" NUMBER, 
	"BAD" NUMBER, 
	"WIN" NUMBER, 
	"TOTAL" NUMBER, 
	"COUNTVOTE" NUMBER, 
	 CONSTRAINT "REPUTATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REPUTATION_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."ELECTION_CANDIDATE" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."ROLE" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"LINKID" VARCHAR2(10 BYTE), 
	 CONSTRAINT "ROLE_FK1" FOREIGN KEY ("LINKID")
	  REFERENCES "ADMIN"."LINK" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."SCANING" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IMAGE" CLOB, 
	"TABLENAME" VARCHAR2(30 BYTE), 
	 CONSTRAINT "SCANING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

 ---
 
  CREATE TABLE "ADMIN"."SCHLOGIN" 
   (	"USERID" VARCHAR2(10 BYTE), 
	"ACTION" VARCHAR2(500 BYTE), 
	"LOG_DATE" DATE, 
	 CONSTRAINT "SCHLOGIN_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."SCHLOGIN_1" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"ACTION" VARCHAR2(20 BYTE), 
	"LOG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."SEARCH_FINGER" 
   (	"PEOPLE_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(10 BYTE), 
	"SDATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"PAGE" VARCHAR2(50 BYTE), 
	 CONSTRAINT "SEARCH_FINGER_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "SEARCH_FINGER_FK2" FOREIGN KEY ("PEOPLE_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."SMS" 
   (	"ID" VARCHAR2(10 BYTE), 
	"SMS" VARCHAR2(100 BYTE), 
	"SDATE" DATE, 
	"PHONE" VARCHAR2(15 BYTE), 
	 CONSTRAINT "SMS_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."TAB_USER" 
   (	"USER_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(10 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT NULL NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"TEMP_EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FOREIGNER" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TAB_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TAB_USER_FK1" FOREIGN KEY ("CREATE_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."TEX" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AMMOUNT" NUMBER, 
	"DUE" NUMBER, 
	 CONSTRAINT "TEX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TEX_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."UPDATE_P_EXTRA" 
   (	"ID" VARCHAR2(10 BYTE), 
	"CODE" NUMBER, 
	 CONSTRAINT "UPDATE_P_EXTRA_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "UPDATE_P_EXTRA_FK2" FOREIGN KEY ("CODE")
	  REFERENCES "ADMIN"."UPDATECODE" ("CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."UPDATE_P_ROLE" 
   (	"ROLE_NAME" VARCHAR2(30 BYTE), 
	"CODE" NUMBER, 
	 CONSTRAINT "UPDATE_P_ROLE_FK1" FOREIGN KEY ("CODE")
	  REFERENCES "ADMIN"."UPDATECODE" ("CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."UPDATE_P_ROLE_FOR_USER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ROLE_NAME" VARCHAR2(30 BYTE), 
	 CONSTRAINT "UPDATE_P_ROLE_FOR_USER_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

 ---
 
  CREATE TABLE "ADMIN"."UPDATECODE" 
   (	"CODE" NUMBER, 
	"COLUMNNAME" VARCHAR2(30 BYTE), 
	"TABLENAME" VARCHAR2(30 BYTE), 
	"IDATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"STATIC" VARCHAR2(1 BYTE) DEFAULT 'n' NOT NULL ENABLE, 
	"USING" VARCHAR2(30 BYTE), 
	 CONSTRAINT "UPDATECODEPK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ADMIN"."UPDATE_CODE_GENERATE" before insert on updatecode
      for each row
    begin
      select code.nextval,upper(:new.columnname),upper(:new.tablename),upper(:new.using)
        into :new.code,:new.columnname,:new.tablename,:new.using
        from dual;
    end;
/
ALTER TRIGGER "ADMIN"."UPDATE_CODE_GENERATE" ENABLE;
 
---

  CREATE TABLE "ADMIN"."USER_ROLE" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "USER_ROLE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."USER_VIEW" 
   (	"ID" VARCHAR2(10 BYTE), 
	"VIEWNAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "USER_VIEW_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."VACTIVITY" 
   (	"QUERY" VARCHAR2(4000 BYTE), 
	"PERFORM_BY" VARCHAR2(10 BYTE), 
	"P_DATE" DATE, 
	 CONSTRAINT "VACTIVITY_FK1" FOREIGN KEY ("PERFORM_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."VISA" 
   (	"ID" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"REASON" VARCHAR2(30 BYTE), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"APROVEBY" VARCHAR2(10 BYTE), 
	"ADATE" DATE, 
	"VISANO" VARCHAR2(10 BYTE), 
	 CONSTRAINT "VISA_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."PASSPORT" ("USER_ID") ENABLE, 
	 CONSTRAINT "VISA_FK2" FOREIGN KEY ("APROVEBY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."VOTER_LIST" 
   (	"ID" VARCHAR2(10 BYTE), 
	"ZONE" NUMBER, 
	 CONSTRAINT "VOTERLISTPK1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "VOTER_LIST_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."PEOPLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."VROLE" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"VIEW_ID" NUMBER, 
	 CONSTRAINT "VROLE_FK1" FOREIGN KEY ("VIEW_ID")
	  REFERENCES "ADMIN"."ALLVIEW" ("VIEW_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."WORK" 
   (	"ID" VARCHAR2(10 BYTE), 
	"DETAILS" VARCHAR2(200 BYTE), 
	"SALARY" NUMBER, 
	"JOIN" DATE, 
	"RESIGN" DATE, 
	"ADD_BY" VARCHAR2(10 BYTE), 
	"ADATE" DATE, 
	"SNO" NUMBER, 
	 CONSTRAINT "WORK_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "WORK_FK2" FOREIGN KEY ("ADD_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_APPOINT" 
   (	"BUS_OWNER" VARCHAR2(10 BYTE), 
	"STUFF_ID" VARCHAR2(10 BYTE), 
	"JOIN_DATE" DATE, 
	"RESIGN_DATE" DATE, 
	"TYPE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "X_APPOINT_FK1" FOREIGN KEY ("BUS_OWNER")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "X_APPOINT_FK2" FOREIGN KEY ("STUFF_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_BAL_HIS" 
   (	"SENDER" VARCHAR2(10 BYTE), 
	"RECEIVER" VARCHAR2(10 BYTE), 
	"TK" NUMBER(6,2), 
	"TRANSFER_DATE" DATE, 
	 CONSTRAINT "X_BAL_HIS_FK1" FOREIGN KEY ("SENDER")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "X_BAL_HIS_FK2" FOREIGN KEY ("RECEIVER")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_BALANCE" 
   (	"ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TK" NUMBER(10,2), 
	 CONSTRAINT "X_BALANCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "X_BALANCE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_BUS_HAS_STOP_OFFICE" 
   (	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"BUS_STOP_POINT" NUMBER, 
	"S_NO" NUMBER, 
	"KM" NUMBER(5,2), 
	"INS_BY" VARCHAR2(10 BYTE), 
	"INS_DATE" DATE, 
	"AUTONUMBER" NUMBER, 
	 CONSTRAINT "X_BUS_HAS_STOP_OFFICE_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE, 
	 CONSTRAINT "X_BUS_HAS_STOP_OFFICE_FK2" FOREIGN KEY ("BUS_STOP_POINT")
	  REFERENCES "ADMIN"."X_STOP_OFFICE" ("STOP_POINT") ENABLE, 
	 CONSTRAINT "X_BUS_HAS_STOP_OFFICE_FK3" FOREIGN KEY ("INS_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_BUS_INFROMATION" 
   (	"OWNER_ID" VARCHAR2(10 BYTE), 
	"LICENSE" VARCHAR2(1 BYTE), 
	"LICENSE_NO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SERVER_NAME" VARCHAR2(50 BYTE), 
	"SERVICE_TYPE" VARCHAR2(10 BYTE), 
	"RENT" NUMBER, 
	"TOTAL_SIT" NUMBER, 
	"TOTAL_STAND" NUMBER, 
	"FITNESS" VARCHAR2(1 BYTE), 
	"TAX" VARCHAR2(4 BYTE), 
	"INSERT_BY" VARCHAR2(10 BYTE), 
	"INSERT_DATE" DATE, 
	 CONSTRAINT "X_BUS_INFROMATION_PK" PRIMARY KEY ("LICENSE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "X_BUS_INFROMATION_FK1" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "X_BUS_INFROMATION_FK2" FOREIGN KEY ("INSERT_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_BUS_STATUS" 
   (	"ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LATITUDE" VARCHAR2(200 BYTE), 
	"LONGITUDE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	 CONSTRAINT "X_BUS_STATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "X_BUS_STATUS_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ADMIN"."BUS_PASS" after update on x_bus_status
for each row
begin
X_PASS(:old.id);

end;
/
ALTER TRIGGER "ADMIN"."BUS_PASS" DISABLE;
 
--

  CREATE TABLE "ADMIN"."X_BUS_STUFF" 
   (	"BUS_LICENSE_NO" VARCHAR2(30 BYTE), 
	"STUFF_ID" VARCHAR2(10 BYTE), 
	"STIME" DATE, 
	"ETIME" DATE, 
	 CONSTRAINT "X_BUS_STUFF_FK1" FOREIGN KEY ("STUFF_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
-----

  CREATE TABLE "ADMIN"."X_COUNTER_STUFF" 
   (	"LOCATION_ID" NUMBER, 
	"STUFF_ID" VARCHAR2(10 BYTE), 
	"STIME" DATE, 
	"ETIME" DATE, 
	 CONSTRAINT "X_COUNTER_STUFF_FK1" FOREIGN KEY ("STUFF_ID")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE, 
	 CONSTRAINT "X_COUNTER_STUFF_FK2" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "ADMIN"."X_STOP_OFFICE" ("STOP_POINT") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."X_STOP_OFFICE" 
   (	"STOP_POINT" NUMBER NOT NULL ENABLE, 
	"LOCATION_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ROAD_NO" VARCHAR2(30 BYTE), 
	"ROAD_NAME" VARCHAR2(50 BYTE), 
	"L1" NUMBER(*,127), 
	"L2" NUMBER(*,127), 
	"L3" NUMBER(*,127), 
	"L4" NUMBER(*,127), 
	"INSERT_BY" VARCHAR2(10 BYTE), 
	"INS_DATE" DATE, 
	 CONSTRAINT "X_STOP_OFFICE_PK" PRIMARY KEY ("LOCATION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "X_STOP_OFFICE_UK1" UNIQUE ("STOP_POINT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "X_STOP_OFFICE_FK1" FOREIGN KEY ("INSERT_BY")
	  REFERENCES "ADMIN"."TAB_USER" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."X_TICKET" 
   (	"S_NO" NUMBER, 
	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"PESSENGER_ID" VARCHAR2(200 BYTE), 
	"TRAVEL_DATE" DATE, 
	"SFROM" VARCHAR2(100 BYTE), 
	"STIME" DATE, 
	"ETO" VARCHAR2(100 BYTE), 
	"ETIME" DATE, 
	"KM" VARCHAR2(20 BYTE), 
	"TAKA" VARCHAR2(20 BYTE), 
	"SIT" VARCHAR2(20 BYTE), 
	"SS_NO" NUMBER, 
	"ES_NO" NUMBER, 
	 CONSTRAINT "X_TICKET_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
----

  CREATE TABLE "ADMIN"."X_TICKET_1" 
   (	"S_NO" NUMBER, 
	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"PESSENGER_ID" VARCHAR2(200 BYTE), 
	"TRAVEL_DATE" DATE, 
	"SFROM" VARCHAR2(100 BYTE), 
	"STIME" DATE, 
	"ETO" VARCHAR2(100 BYTE), 
	"ETIME" DATE, 
	"KM" VARCHAR2(20 BYTE), 
	"TAKA" VARCHAR2(20 BYTE), 
	"SIT" VARCHAR2(20 BYTE), 
	"SS_NO" NUMBER, 
	"ES_NO" NUMBER, 
	 CONSTRAINT "X_TICKET_1_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_TICKET_P" 
   (	"S_NO" NUMBER, 
	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"PESSENGER_ID" VARCHAR2(200 BYTE), 
	"TRAVEL_DATE" DATE, 
	"SFROM" VARCHAR2(100 BYTE), 
	"STIME" DATE, 
	"ETO" VARCHAR2(100 BYTE), 
	"ETIME" DATE, 
	"KM" VARCHAR2(20 BYTE), 
	"TAKA" VARCHAR2(20 BYTE), 
	"SIT" VARCHAR2(20 BYTE), 
	"SS_NO" NUMBER, 
	"ES_NO" NUMBER, 
	 CONSTRAINT "X_TICKET_P_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_TIME_SCHEDULE" 
   (	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"BUS_STOP_POINT" NUMBER, 
	"TIME" DATE, 
	"PASS" NUMBER, 
	 CONSTRAINT "X_TIME_SCHEDULE_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_TIME_SCHEDULE_1" 
   (	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"BUS_STOP_POINT" NUMBER, 
	"TIME" DATE, 
	"PASS" NUMBER, 
	 CONSTRAINT "X_TIME_SCHEDULE_1_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
---

  CREATE TABLE "ADMIN"."X_TIME_SCHEDULE_C" 
   (	"S_NO" NUMBER, 
	"BUS_LICENSE_NO" VARCHAR2(50 BYTE), 
	"BUS_STOP_POINT" NUMBER, 
	"TIME" DATE, 
	"PASS" NUMBER, 
	 CONSTRAINT "X_TIME_SCHEDULE_C_FK1" FOREIGN KEY ("BUS_LICENSE_NO")
	  REFERENCES "ADMIN"."X_BUS_INFROMATION" ("LICENSE_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ADMIN"."MAINTAIN_TIME_SCHEDULE" after insert or delete or update on x_time_schedule_c
for each row
begin
if inserting then
update X_BUS_INFROMATION set license='c' where LICENSE_NO=:new.bus_license_no;
elsif deleting then
update X_BUS_INFROMATION set license='c' where LICENSE_NO=:old.bus_license_no;
x_cancel_ticket(:old.bus_license_no);

else
update X_BUS_INFROMATION set license='c' where LICENSE_NO=:old.bus_license_no;
x_cancel_ticket(:old.bus_license_no);
end if;
end;
/
ALTER TRIGGER "ADMIN"."MAINTAIN_TIME_SCHEDULE" ENABLE;
 
---


 
 